CC=gcc
CFLAGS = -Wall -pedantic -std=c90
LDFLAGS = -lm
SRC = CommandDispatcher.c CommandParser.c HashMap.c SetMap.c set.c Errors.c myset.c
OBJ = $(SRC:.c=.o)
EXEC = myset

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(OBJ) $(LDFLAGS) -o $(EXEC)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)